workflows:
  build_and_deploy_gke:
    jobs:
      - runner/docker_build_gke:
          filters: 
            branches:
              only: 
                - main
          docker_image_full: &docker_image_gcloud << pipeline.parameters.service_docker_image_full_gcloud >>
          context: &context_gke [domain=nugraph_production, dockerhub]
          copy_vendor: false
      - runner/deploy_gke:
          requires:
            - runner/docker_build_gke
          kubernetes_namespace: nugraph
          gke_cluster: ${GKE_CLUSTER_NAME:?}
          gke_compute_zone: europe-west1-b
          docker_image_full: *docker_image_gcloud
          kubernetes_yamls_path: kubernetes
          context: *context_gke

parameters:
  service_docker_image_full_gcloud:
    type: string
    default: eu.gcr.io/${GCLOUD_PROJECT_ID:?}/${CIRCLE_PROJECT_REPONAME:?}:<<pipeline.number>>_${CIRCLE_SHA1::6}

version: 2.1
orbs:
  runner: graphmasters/runner@0.4.0